version: '3.7'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/tmp_env.docker
    environment:
      - FRONTEND_URL=""
      - CMNSRV_CLIENTID="CEM_SERVICE_CLIENT"
    ports:
      - '3000:3000'
  frontend:
    image: 'node:lts-alpine3.12'
    entrypoint:
      - 'sh'
      - '-c'
      - 'npm install && npm run dev'
    working_dir: '/app'
    ports:
      - '8080:8080'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
