version: '3.7'
services:
  backend:
    image: 'node:lts-alpine3.12'
    entrypoint:
      - 'sh'
      - '-c'
      - 'npm install && npm run dev'
    working_dir: '/app'
    ports:
      - '3000:3000'
    environment:
      - CLIENT_ID="${CLIENT_ID:-CEM_SERVICE_CLIENT}"
      - CLIENT_SECRET="${CLIENT_SECRET}"
    volumes:
      - './backend:/app'
      - '/app/node_modules'
  frontend:
    depends_on:
      - backend
    image: 'node:lts-alpine3.12'
    entrypoint:
      - 'sh'
      - '-c'
      - 'npm install && npm run dev'
    working_dir: '/app'
    ports:
      - '8080:8080'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
