---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${BACKEND_COMPONENT}
labels:
  app: ${APP}
  component: ${BACKEND_COMPONENT}
parameters:
  - name: APP
    required: true
  - name: BACKEND_COMPONENT
    required: true
  - name: BACKEND_PORT
    required: true
  - name: FRONTEND_COMPONENT
    required: true
  - name: FRONTEND_PORT
    required: true
  - name: NAMESPACE_DEPLOY
    required: true
  - name: NAMESPACE_TOOLS
    required: true
  - name: DOMAIN
    required: true
  - name: DOCKER_SRC
    required: true
  - name: BUILD_TAG
    required: true
  - name: GIT_URL
    required: true
  - name: GIT_BRANCH
    required: true
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP}
        component: ${BACKEND_COMPONENT}
      name: ${APP}-${BACKEND_COMPONENT}
      namespace: ${NAMESPACE_TOOLS}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP}
        component: ${BACKEND_COMPONENT}
      name: ${APP}-${BACKEND_COMPONENT}
      namespace: ${NAMESPACE_TOOLS}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP}-${BACKEND_COMPONENT}:${BUILD_TAG}
      source:
        dockerfile: |
          FROM ${DOCKER_SRC}

          EXPOSE "${BACKEND_PORT:-3000}"

          USER root
          WORKDIR /app
          RUN git clone ${GIT_URL} -b ${GIT_BRANCH} /tmp/app && \
              cp -rT /tmp/app/backend . && \
              rm -rf /tmp/app
          RUN npm install

          CMD npm start
        type: Dockerfile
      strategy:
        type: Docker
      triggers:
        - imageChange: {}
          type: ImageChange
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${BACKEND_COMPONENT}
      name: ${APP}-${BACKEND_COMPONENT}
      namespace: ${NAMESPACE_DEPLOY}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        component: ${BACKEND_COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP}
            component: ${BACKEND_COMPONENT}
        spec:
          containers:
            - env:
              image: ${APP}-${BACKEND_COMPONENT}
              name: ${APP}-${BACKEND_COMPONENT}
              ports:
                - containerPort: ${{BACKEND_PORT}}
              resources: {}
              workingDir: /app
              env:
                - name: FRONTEND_URL
                  value: https://${APP}-${FRONTEND_COMPONENT}-${NAMESPACE_DEPLOY}.${DOMAIN}
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: CLIENT_ID
                      name: cem-backend
                - name: CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: CLIENT_SECRET
                      name: cem-backend
              name: ${APP}-${BACKEND_COMPONENT}
              namespace: ${NAMESPACE_TOOLS}
              ports:
                - containerPort: ${{BACKEND_PORT}}
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${BACKEND_COMPONENT}
            from:
              kind: ImageStreamTag
              name:  ${APP}-${BACKEND_COMPONENT}:${BUILD_TAG}
              namespace: ${NAMESPACE_TOOLS}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${BACKEND_COMPONENT}
      name: ${APP}-${BACKEND_COMPONENT}
      namespace: ${NAMESPACE_DEPLOY}
    spec:
      ports:
      - name: "${BACKEND_PORT}"
        port: ${{BACKEND_PORT}}
        targetPort: ${{BACKEND_PORT}}
      selector:
        app: ${APP}
        component: ${BACKEND_COMPONENT}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP}
        component: ${BACKEND_COMPONENT}
      name: ${APP}-${BACKEND_COMPONENT}
      namespace: ${NAMESPACE_DEPLOY}
    spec:
      host: ${APP}-${BACKEND_COMPONENT}-${NAMESPACE_DEPLOY}.${DOMAIN}
      port:
        targetPort: ${{BACKEND_PORT}}
      to:
        kind: Service
        name: ${APP}-${BACKEND_COMPONENT}
      tls:
        termination: edge
