apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    io.kompose.service: backend
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - command:
            - sh
            - -c
            - npm install && npm run dev
          env:
            - name: CLIENT_ID
              value: '"CEM_SERVICE_CLIENT"'
            - name: CLIENT_SECRET
              value: '""'
          image: ' '
          name: backend
          ports:
            - containerPort: 3000
          resources: {}
          workingDir: /app
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - backend
        from:
          kind: ImageStreamTag
          name: backend:lts-alpine3.12
      type: ImageChange
status: {}
