---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${COMPONENT}
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: cem
  - name: COMPONENT
    value: backend
  - name: NAMESPACE_DEPLOY
    value: csnr-devops-lab-deploy
  - name: CLIENT_ID
    value: CEM_SERVICE_CLIENT
  - name: CLIENT_SECRET
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: ${APP}
      name: ${APP}-${COMPONENT}
      namespace: ${NAMESPACE_DEPLOY}
    stringData:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: '${CLIENT_SECRET}'
