---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${COMPONENT}
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: cem
  - name: COMPONENT
    value: backend
  - name: COMPONENT_FRONTEND
    value: frontend
  - name: PORT
    value: '3000'
  - name: COMPONENT_FRONTEND
    value: frontend
  - name: PORT_FRONTEND
    value: '8080'
  - name: DOMAIN
    value: pathfinder.gov.bc.ca
  - name: IMG_TAG
    value: latest
  - name: NAMESPACE_DEPLOY
    value: csnr-devops-lab-deploy
  - name: NAMESPACE_TOOLS
    value: csnr-devops-lab-tools
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
      namespace: ${NAMESPACE_DEPLOY}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        component: ${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP}
            component: ${COMPONENT}
        spec:
          containers:
            - env:
              image: ${APP}-${COMPONENT}
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{PORT}}
              resources: {}
              workingDir: /app
              env:
                - name: FRONTEND_URL
                  value: https://${APP}-${COMPONENT_FRONTEND}-${NAMESPACE_DEPLOY}.${DOMAIN}
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: CLIENT_ID
                      name: cem-backend
                - name: CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: CLIENT_SECRET
                      name: cem-backend
              name: ${APP}-${COMPONENT}
              namespace: ${NAMESPACE_TOOLS}
              ports:
                - containerPort: ${{PORT}}
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name:  ${APP}-${COMPONENT}:${IMG_TAG}
              namespace: ${NAMESPACE_TOOLS}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
      namespace: ${NAMESPACE_DEPLOY}
    spec:
      ports:
      - name: "${PORT}"
        port: ${{PORT}}
        targetPort: ${{PORT}}
      selector:
        app: ${APP}
        component: ${COMPONENT}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
      namespace: ${NAMESPACE_DEPLOY}
    spec:
      host: ${APP}-${COMPONENT}-${NAMESPACE_DEPLOY}.${DOMAIN}
      port:
        targetPort: ${PORT}
      to:
        kind: Service
        name: ${APP}-${COMPONENT}
      tls:
        termination: edge
