---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${COMPONENT}
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: cem
  - name: COMPONENT
    value: frontend
  - name: APP_NAMESPACE
    value: csnr-devops-lab-deploy
  - name: DOMAIN
    value: pathfinder.gov.bc.ca
  - name: IMG_TAG
    value: latest
  - name: IMG_NAMESPACE
    value: csnr-devops-lab-deploy
  - name: PORT
    value: '8080'
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        component: ${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP}
            component: ${COMPONENT}
        spec:
          containers:
            - env:
              image: ${APP}-${COMPONENT}
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{PORT}}
              resources: {}
              workingDir: /app
              namespace: ${IMG_NAMESPACE}
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{PORT}}
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name: ${APP}-${COMPONENT}:${IMG_TAG}
              namespace: ${IMG_NAMESPACE}
          type: ImageChange
