apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    io.kompose.service: frontend
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - command:
        - sh
        - -c
        - npm install && npm run dev
        image: ' '
        name: frontend
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: frontend-claim0
        - mountPath: /app/node_modules
          name: frontend-claim1
        workingDir: /app
      restartPolicy: Always
      volumes:
      - name: frontend-claim0
        persistentVolumeClaim:
          claimName: frontend-claim0
      - name: frontend-claim1
        persistentVolumeClaim:
          claimName: frontend-claim1
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - frontend
      from:
        kind: ImageStreamTag
        name: frontend:lts-alpine3.12
    type: ImageChange
status: {}
