apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: node:lts-alpine3.12
    generation: null
    importPolicy: {}
    name: lts-alpine3.12
status:
  dockerImageRepository: ""
