---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${COMPONENT}
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: cem
  - name: COMPONENT
    value: frontend
  - name: PORT
    value: '8080'
  - name: COMPONENT_BACKEND
    value: backend
  - name: PORT_BACKEND
    value: '3000'
  - name: APP_NAMESPACE
    value: csnr-devops-lab-deploy
  - name: DOMAIN
    value: pathfinder.gov.bc.ca
  - name: IMG_TAG
    value: latest
  - name: IMG_NAMESPACE
    value: csnr-devops-lab-deploy
objects:
  - apiVersion: v1
    kind: ConfigMap
    data:
      config.json: |
        {
          "backendUrl": "https://${APP}-${COMPONENT_BACKEND}-${APP_NAMESPACE}.${DOMAIN}"
        }
    metadata:
      labels:
        app: ${APP}
      name: ${APP}-${COMPONENT}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        component: ${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP}
            component: ${COMPONENT}
        spec:
          containers:
            - env:
                - name: BACKEND_URL
                  value: https://${APP}-${COMPONENT_BACKEND}-${APP_NAMESPACE}.${DOMAIN}
              image: ${APP}-${COMPONENT}
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{PORT}}
              resources: {}
              volumeMounts:
                - name: cem-frontend
                  mountPath: /app/dist/config.json
                  subPath: config.json
                  readOnly: true
              workingDir: /app
              namespace: ${IMG_NAMESPACE}
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{PORT}}
          restartPolicy: Always
          volumes:
            - name: cem-frontend
              configMap:
                name: cem-frontend
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name: ${APP}-${COMPONENT}:${IMG_TAG}
              namespace: ${IMG_NAMESPACE}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      ports:
      - name: "${PORT}"
        port: ${{PORT}}
        targetPort: ${{PORT}}
      selector:
        app: ${APP}
        component: ${COMPONENT}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      host: ${APP}-${COMPONENT}-${APP_NAMESPACE}.${DOMAIN}
      port:
        targetPort: ${PORT}
      to:
        kind: Service
        name: ${APP}-${COMPONENT}
      tls:
        termination: edge
