version: '3.8'

networks:
  comfort-net:
    driver: "bridge"

services:

  postgres:
    container_name: comfort_postgres
    image: postgres:10
    restart: always
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_DB=${DB_DATABASE}"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - comfort-net

  node_migrate:
    depends_on:
      - postgres
    container_name: comfort_node_migrate
    restart: on-failure
    build:
      context: ../app
      dockerfile: migration.Dockerfile
    environment:
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_PORT=${DB_PORT}"
    entrypoint: ["/bin/sh", "/opt/app-root/src/bin/run-migrations.sh"]
    networks:
      - comfort-net
